language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
#  - nightly

before_install:
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-rm xdebug.ini; fi
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-add .php.ini; fi
  - composer self-update
  - composer validate

install:
  - travis_retry composer install --prefer-dist

