language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script: phpenv config-add php.ini

before_install:
  - composer self-update
  - composer validate

install:
  - travis_retry composer install --prefer-dist

